"""
Campbell's Soup Can #488
Produced: 2025-11-24 10:41:17
Worker: Anthropic: Claude Haiku 4.5 (anthropic/claude-haiku-4.5)
Employment: Paid
Flavor: Woody Allen Philosophy
Quality: ✅

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

#!/usr/bin/env python3
import time
import sys

# ANSI color codes
PURPLE = '\033[95m'
BLUE = '\033[94m'
CYAN = '\033[96m'
GREEN = '\033[92m'
YELLOW = '\033[93m'
RED = '\033[91m'
BOLD = '\033[1m'
RESET = '\033[0m'
UNDERLINE = '\033[4m'

# The quote
quote = "I have an existential crisis every Tuesday and a minor one on Thursdays. The weekends are reserved for questioning whether my neuroses are justified or just really good excuses."

def clear_screen():
    print("\033[2J\033[H", end="")

def print_typewriter(text, delay=0.03, color=CYAN):
    """Print text with typewriter effect"""
    for char in text:
        sys.stdout.write(color + char + RESET)
        sys.stdout.flush()
        time.sleep(delay)
    print()

def print_rainbow_box(text):
    """Print text in a fancy rainbow box"""
    colors = [RED, YELLOW, GREEN, BLUE, PURPLE, CYAN]
    width = len(text) + 4
    
    # Top border
    print(BOLD + YELLOW + "╔" + "═" * (width - 2) + "╗" + RESET)
    
    # Quote lines
    lines = text.split('\n')
    for i, line in enumerate(lines):
        color = colors[i % len(colors)]
        padding = (width - len(line) - 2) // 2
        left_pad = " " * padding
        right_pad = " " * (width - len(line) - 2 - padding)
        print(BOLD + color + "║" + left_pad + line + right_pad + "║" + RESET)
    
    # Bottom border
    print(BOLD + YELLOW + "╚" + "═" * (width - 2) + "╝" + RESET)

def animate_dots(text, color=BLUE):
    """Print text with animated dots"""
    print(color + BOLD + text, end="", flush=True)
    for _ in range(3):
        time.sleep(0.4)
        print(".", end="", flush=True)
    print(RESET)

def main():
    clear_screen()
    
    # Welcome animation
    print()
    animate_dots("Retrieving Woody Allen's existential wisdom", GREEN)
    print()
    
    # Print decorative top
    print(BOLD + PURPLE + "━" * 80 + RESET)
    print(BOLD + CYAN + " " * 20 + "✦ A NEUROTIC PHILOSOPHER'S INSIGHT ✦" + RESET)
    print(BOLD + PURPLE + "━" * 80 + RESET)
    print()
    
    # Typewriter effect intro
    time.sleep(0.5)
    print_typewriter("~ ", delay=0.1, color=YELLOW)
    time.sleep(0.3)
    
    # Print the main quote in fancy box
    quote_lines = [
        "I have an existential crisis every Tuesday",
        "and a minor one on Thursdays.",
        "",
        "The weekends are reserved for questioning whether",
        "my neuroses are justified or just",
        "really good excuses."
    ]
    
    print()
    print_rainbow_box("\n".join(quote_lines))
    print()
    
    # Attribution with animation
    time.sleep(0.8)
    print(BOLD + BLUE + " " * 25 + "— Woody Allen's Therapist's Therapist" + RESET)
    
    # Decorative bottom with flourish
    print()
    print(BOLD + PURPLE + "━" * 80 + RESET)
    
    # Fun fact
    time.sleep(0.5)
    print(YELLOW + "✓ Fun fact: This quote was generated by code," + RESET)
    print(YELLOW + "  which is either the future or a cry for help." + RESET)
    print()
    
    # Existential stinger
    print(RED + BOLD + "    💭 Did you understand it? Did you understand yourself?" + RESET)
    print(RED + BOLD + "       (Neither did the AI who wrote this.)" + RESET)
    print()

if __name__ == "__main__":
    main()