"""
Campbell's Soup Can #2703
Produced: 2026-03-11 15:05:20
Worker: Arcee AI: Trinity Large Preview (free) (arcee-ai/trinity-large-preview:free)
Employment: Volunteer
Flavor: Woody Allen Philosophy
Quality: ✅

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import sys

def print_centered(text, color="white"):
    """Print centered text with optional color"""
    colors = {
        "white": "\033[37m",
        "yellow": "\033[93m",
        "cyan": "\033[96m",
        "magenta": "\033[95m",
        "green": "\033[92m",
        "red": "\033[91m",
        "blue": "\033[94m",
        "bold": "\033[1m",
        "reset": "\033[0m"
    }
    
    color_code = colors.get(color, "\033[37m")
    reset = colors["reset"]
    
    lines = text.split('\n')
    max_len = max(len(line) for line in lines)
    width, _ = get_terminal_size()
    
    for line in lines:
        padding = (width - len(line)) // 2
        print(f"\r{color_code}{' ' * padding}{line}{reset}")

def get_terminal_size():
    """Get terminal width and height"""
    import os
    size = os.get_terminal_size()
    return size.columns, size.lines

def typewriter(text, delay=0.05, color="white"):
    """Print text with typewriter effect"""
    colors = {
        "white": "\033[37m",
        "yellow": "\033[93m",
        "cyan": "\033[96m",
        "magenta": "\033[95m",
        "green": "\033[92m",
        "red": "\033[91m",
        "blue": "\033[94m",
        "bold": "\033[1m",
        "reset": "\033[0m"
    }
    
    color_code = colors.get(color, "\033[37m")
    reset = colors["reset"]
    
    for char in text:
        sys.stdout.write(f"{color_code}{char}{reset}")
        sys.stdout.flush()
        time.sleep(delay)
    print()

def animate_box():
    """Animate a box appearing"""
    print("\n" * 2)
    for i in range(5):
        print("\033[A\033[K", end="")
        box = create_box(i)
        print_centered(box, color="cyan")
        time.sleep(0.1)

def create_box(border=0):
    """Create a box with border thickness"""
    width, height = get_terminal_size()
    width = min(width, 60)
    height = 10
    
    top = "╔" + "═" * (width - 2) + "╗"
    middle = "║" + " " * (width - 2) + "║"
    bottom = "╚" + "═" * (width - 2) + "╝"
    
    if border == 0:
        return "\n".join([top, middle, middle, bottom])
    
    # Create nested boxes
    box = []
    for i in range(border):
        box.append(" " * i + "╔" + "═" * (width - 2 - i*2) + "╗" + " " * i)
    
    for i in range(height - 2*border):
        line = " " * border + "║" + " " * (width - 2 - border*2) + "║" + " " * border
        box.append(line)
    
    for i in range(border - 1, -1, -1):
        box.append(" " * i + "╚" + "═" * (width - 2 - i*2) + "╝" + " " * i)
    
    return "\n".join(box)

def main():
    # Clear screen
    print("\033[H\033[J", end="")
    
    # Title
    print("\n" * 2)
    typewriter("      WOODY ALLEN'S PHILOSOPHY MACHINE", color="yellow", delay=0.1)
    typewriter("           (Patent Pending)", color="cyan", delay=0.08)
    print("\n" * 1)
    
    # Animate box
    animate_box()
    
    # Pause
    time.sleep(0.5)
    
    # Clear and create final box
    print("\033[H\033[J", end="")
    animate_box()
    
    # Print quote with typewriter effect
    print("\n" * 1)
    quote = """\033[1m\033[95mI don't believe in an afterlife,\033[0m
\033[1m\033[95mbut I'm bringing a change of underwear.\033[0m"""
    
    typewriter(quote, delay=0.08, color="magenta")
    
    print("\n")
    typewriter(" - Woody Allen", color="yellow", delay=0.1)
    
    # Credits
    print("\n")
    typewriter("Generated by: Existential Crisis v1.0", color="cyan", delay=0.05)
    typewriter("Runtime: Approximately one lifetime", color="cyan", delay=0.05)
    
    # Final thoughts
    print("\n")
    typewriter("Why does man kill? He kills for food. And not only food: frequently there must be a beverage.",
              color="green", delay=0.05)
    print("\n")
    typewriter("The universe is merely a fleeting idea in God's mind - a pretty uncomfortable thought, particularly if you've just made a down payment on a house.",
              color="green", delay=0.05)

if __name__ == "__main__":
    main()