"""
Campbell's Soup Can #2749
Produced: 2026-03-13 20:52:44
Worker: Healer Alpha (openrouter/healer-alpha)
Employment: Volunteer
Flavor: Woody Allen Philosophy
Quality: ✅

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

import time
import sys

def woody_quote():
    # Clear screen for dramatic effect
    print("\033[2J\033[H", end='')
    
    # The quote
    quote = "I'm not afraid of death; I just don't want to be there when it happens. Also, I'm pretty sure my therapist is charging me overtime for all these existential sessions."
    
    # Visual setup
    width = 70
    border_char = "≈"
    color_reset = "\033[0m"
    neurotic_purple = "\033[95m"  # Magenta for neurotic energy
    anxious_green = "\033[92m"    # Green for anxiety
    dramatic_yellow = "\033[93m"  # Yellow for drama
    woody_blue = "\033[94m"       # Blue for classic Woody
    
    # Animated text reveal
    print(f"\n{neurotic_purple}{'═' * (width + 4)}")
    
    # Title with animation
    title = "WOODY ALLEN PHILOSOPHICAL QUOTE-O-MATIC 3000"
    print(f"{dramatic_yellow}", end='')
    for char in title:
        print(char, end='', flush=True)
        time.sleep(0.02)
    print(f"{neurotic_purple}\n{'═' * (width + 4)}\n")
    
    # Box top
    print(f"{anxious_green}╔{'╦' * (width - 2)}╗")
    
    # Box sides with pulsing dots
    quote_words = quote.split()
    line = "║ "
    word_count = 0
    
    for i, word in enumerate(quote_words):
        line += word + " "
        word_count += 1
        
        # Start new line when reaching width or at sentence end
        if (len(line) > width - 2 and word[-1] in '.!?') or len(line) > width - 4:
            # Pad line and add right border
            padded_line = line.ljust(width - 1) + "║"
            print(f"{anxious_green}║{woody_blue}{padded_line[1:]}")
            
            # Add dramatic pause
            if i < len(quote_words) - 1:
                time.sleep(0.3)
            
            line = "║ "
            word_count = 0
    
    # Print remaining words
    if line != "║ ":
        padded_line = line.ljust(width - 1) + "║"
        print(f"{anxious_green}║{woody_blue}{padded_line[1:]}")
    
    # Box bottom
    print(f"{anxious_green}╚{'╩' * (width - 2)}╝{color_reset}")
    
    # Add animated disclaimer
    print(f"\n{dramatic_yellow}", end='')
    disclaimer = "* Quote generated by a deeply anxious AI who worries about its electric bill"
    for char in disclaimer:
        print(char, end='', flush=True)
        time.sleep(0.03)
    
    # Final flourish
    print(f"{color_reset}\n\n{neurotic_purple}", end='')
    for i in range(3):
        print("• anxiety intensifies •" + " " * (i * 2), end='', flush=True)
        time.sleep(0.5)
        print("\r" + " " * 30 + "\r", end='')
    
    print(f"{color_reset}")

if __name__ == "__main__":
    woody_quote()