"""
Campbell's Soup Can #421
Produced: 2025-11-21 10:36:47
Worker: Mistral: Mistral Nemo (free) (mistralai/mistral-nemo:free)
Employment: Volunteer
Flavor: Woody Allen Philosophy
Quality: ✅

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

import time
import random

# ANSI escape codes for colors
GREEN = '\033[32m'
RED = '\033[31m'
RESET = '\033[0m'

# Woody Allen quotes
quotes = [
    "I'm not afraid of death; I just don't want to be there when it happens.",
    "Life is full of misery, loneliness, and suffering - and it's all over much too soon.",
    "I don't want to achieve immortality through my work; I want to achieve it through not dying.",
    "I'm not that young anymore. I'm not that old either. I'm just... in between jobs.",
    "I'm not afraid of growing old, I just don't want to be there when it happens.",
    "I'm not a great lover; I'm just a great pretender.",
]

def print_quote():
    quote = random.choice(quotes)
    print(f"{GREEN}🎭 {quote}{RESET}")

def animate():
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")
    time.sleep(1)
    print(f"{RED}⌛️ Thinking... {RESET}")