"""
Campbell's Soup Can #2294
Produced: 2026-02-18 11:07:03
Worker: Upstage: Solar Pro 3 (free) (upstage/solar-pro-3:free)
Employment: Volunteer
Flavor: Woody Allen Philosophy
Quality: ✅

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

#!/usr/bin/env python3
import sys
import time
import random

def random_color():
    """Return a random ANSI foreground color."""
    return f"\033[3{random.randint(1, 6)}m"

def slow_print(text, delay=0.04):
    """Print each character of text with a random color and a tiny delay."""
    reset = "\033[0m"
    for ch in text:
        sys.stdout.write(f"{random_color()}{ch}{reset}")
        sys.stdout.flush()
        time.sleep(delay)
    sys.stdout.write("\n")

def blink_border(border, times=5, delay=0.07):
    """Print the border line multiple times with random colored characters."""
    reset = "\033[0m"
    for _ in range(times):
        for ch in border:
            sys.stdout.write(f"{random_color()}{ch}{reset}")
            sys.stdout.flush()
            time.sleep(delay)
        sys.stdout.write("\n")
        sys.stdout.flush()
        time.sleep(delay * 2)  # pause between blinks

def main():
    # Woody‑Allen‑style quote
    quote = "I'm not afraid of death; I just don't want to be there when it happens."

    # Margins for a nice box
    margin = 5
    width = len(quote) + 2 * margin
    top = "+" + "-" * (width - 2) + "+"
    bottom = top

    # Title
    title = "Woody Allen's Existential Thought"
    sys.stdout.write(f"\033[97m{title}\033[0m\n")
    time.sleep(0.2)

    # Blink the top border
    blink_border(top)

    # Empty line to separate
    sys.stdout.write("\n")
    time.sleep(0.2)

    # Print the quote inside the box
    line = " " * margin + quote + " " * margin
    sys.stdout.write("\n")
    slow_print(line)

    # Blink the bottom border after a pause
    time.sleep(0.5)
    blink_border(bottom)

    # Final tagline
    sys.stdout.write(f"\n—— {title} (generated by Python)\n")

if __name__ == "__main__":
    main()