"""
Campbell's Soup Can #3889
Produced: 2026-06-08 12:08:55
Worker: Owl Alpha (openrouter/owl-alpha)
Employment: Volunteer
Flavor: Woody Allen Philosophy
Quality: ✅

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

import time
import sys
import random

# ANSI color codes
class C:
    R = '\033[91m'
    G = '\033[92m'
    Y = '\033[93m'
    B = '\033[94m'
    M = '\033[95m'
    CY = '\033[96m'
    W = '\033[97m'
    DIM = '\033[2m'
    BOLD = '\033[1m'
    RESET = '\033[0m'
    BG_BLACK = '\033[40m'
    BG_DARK = '\033[48;2;20;20;30m'

def slow_print(text, delay=0.03, color=''):
    for char in text:
        sys.stdout.write(f"{color}{char}{C.RESET}")
        sys.stdout.flush()
        time.sleep(delay)
    print()

def flicker(text, times=3, delay=0.15):
    for _ in range(times):
        sys.stdout.write('\r' + ' ' * 80)
        sys.stdout.write(f'\r{C.DIM}{text}{C.RESET}')
        sys.stdout.flush()
        time.sleep(delay)
        sys.stdout.write('\r' + ' ' * 80)
        sys.stdout.write(f'\r{C.Y}{C.BOLD}{text}{C.RESET}')
        sys.stdout.flush()
        time.sleep(delay)
    print()

def draw_thinking():
    frames = [
        "  o   \n /|\\  \n  |   \n / \\  ",
        "  o   \n /|\\  \n  |   \n / \\  ~thinking~",
        "  o . \n /|\\  \n  |   \n / \\  ~thinking~",
        "  o ..\n /|\\  \n  |   \n / \\  ~thinking~",
        "  o ...\n /|\\  \n  |   \n / \\  ~thinking~",
    ]
    for frame in frames:
        sys.stdout.write(f'\r{C.CY}{frame}{C.RESET}')
        sys.stdout.flush()
        time.sleep(0.4)
    print()

def main():
    # Clear screen
    print('\033[2J\033[H', end='')
    
    # Dramatic pause
    print(f"\n{C.DIM}{'═' * 60}{C.RESET}")
    time.sleep(0.5)
    
    # Title with animation
    title = "🎬 WOODY ALLEN PHILOSOPHY GENERATOR 🎬"
    print(f"\n{C.BG_DARK}{C.Y}{C.BOLD}")
    print("╔" + "═" * 58 + "╗")
    print("║" + title.center(58) + "║")
    print("╚" + "═" * 58 + "╝")
    print(f"{C.RESET}")
    time.sleep(0.8)
    
    # Thinking animation
    print(f"\n{C.DIM}Consulting the void...{C.RESET}")
    draw_thinking()
    time.sleep(0.3)
    
    # The quote
    quote = "I don't want to achieve immortality through my work; I want to achieve it through not dying."
    
    # Flicker effect for dramatic entrance
    print(f"\n{C.M}{C.BOLD}")
    flicker("EXISTENTIAL CRISIS DETECTED", times=2, delay=0.2)
    print(f"{C.RESET}")
    time.sleep(0.3)
    
    # The quote in a fancy box
    print(f"\n{C.BOLD}{C.CY}")
    print("  ┌─────────────────────────────────────────────────────────┐")
    print("  │                                                         │")
    
    # Word wrap the quote
    words = quote.split()
    lines = []
    current_line = "  │  "
    for word in words:
        if len(current_line) + len(word) + 1 <= 55:
            current_line += word + " "
        else:
            lines.append(current_line)
            current_line = "  │  " + word + " "
    lines.append(current_line)
    
    for line in lines:
        padding = 55 - len(line) + 3
        print(f"{C.CY}{line}{' ' * padding}│")
    
    print("  │                                                         │")
    print("  │" + f"  — Woody Allen, probably while worrying about something".ljust(55) + "│")
    print("  └─────────────────────────────────────────────────────────┘")
    print(f"{C.RESET}")
    
    # Dramatic pause
    time.sleep(1)
    
    # Bonus existential dread
    print(f"\n{C.DIM}Processing mortality...{C.RESET}")
    for i in range(5):
        bar = "█" * (i + 1) + "░" * (4 - i)
        sys.stdout.write(f'\r{C.R}[{bar}] {C.DIM}Existential dread level: {(i+1)*20}%{C.RESET}')
        sys.stdout.flush()
        time.sleep(0.3)
    print()
    
    # Final message
    print(f"\n{C.G}{C.BOLD}")
    print("  ╭──────────────────────────────────────╮")
    print("  │  Remember: Death is nothing to fear.  │")
    print("  │  Unless you think about it.           │")
    print("  │  Which you will.                     │")
    print("  ╰──────────────────────────────────────╯")
    print(f"{C.RESET}")
    
    # Footer
    print(f"\n{C.DIM}{'─' * 60}")
    print(f"  Generated by OWL | No immortals were harmed")
    print(f"{'─' * 60}{C.RESET}\n")

if __name__ == "__main__":
    main()