"""
Campbell's Soup Can #2819
Produced: 2026-03-17 20:57:26
Worker: Healer Alpha (openrouter/healer-alpha)
Employment: Volunteer
Flavor: Woody Allen Philosophy
Quality: ✅

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

import time
import sys

def print_color(text, color_code):
    """Print text with ANSI color codes"""
    print(f"\033[{color_code}m{text}\033[0m", end="")

def woody_allen_quote():
    # The quote
    quote = "I'm not afraid of death; I just don't want to be there when it happens."
    
    # ANSI color codes
    RED = "91"
    YELLOW = "93"
    CYAN = "96"
    MAGENTA = "95"
    GREEN = "92"
    
    # ASCII art frame
    frame_top = "╔" + "═" * (len(quote) + 4) + "╗"
    frame_bottom = "╚" + "═" * (len(quote) + 4) + "╝"
    frame_side = "║"
    
    # Clear screen
    print("\033[2J\033[H", end="")
    
    # Animated typing effect
    print_color("Loading existential crisis...", MAGENTA)
    print("\n")
    time.sleep(0.5)
    
    # Print top frame
    print_color(frame_top, YELLOW)
    print()
    
    # Print quote with animation
    print_color(frame_side + " ", YELLOW)
    for char in quote:
        print_color(char, CYAN)
        sys.stdout.flush()
        time.sleep(0.03)
    print_color(" " + frame_side, YELLOW)
    print()
    
    # Print bottom frame
    print_color(frame_bottom, YELLOW)
    print("\n")
    
    # Signature
    print_color("                    - Woody Allen", RED)
    print("\n")
    
    # Visual effects
    print_color("⭐", YELLOW)
    print_color("  ", "")
    print_color("Existential Crisis", GREEN)
    print_color("  ", "")
    print_color("⭐", YELLOW)
    print("\n")
    
    # Philosophical footnote
    print_color("P.S. ", MAGENTA)
    print_color("This quote was generated by a programmer who's equally neurotic about life and code.", CYAN)
    print("\n")
    
    # ASCII art decoration
    print_color("     /\\_/\\  ", GREEN)
    print_color("    ( o.o ) ", GREEN)
    print_color("     > ^ <  ", GREEN)
    print_color("   /|   |\\ ", GREEN)
    print_color("  (_|   |_)  ", GREEN)
    print_color("    Anxiety", YELLOW)
    print_color("    is my", YELLOW)
    print_color("   spirit", YELLOW)
    print_color("    animal", YELLOW)
    print("\n")
    
    # Final thought
    print_color("Remember: ", MAGENTA)
    print_color("If you're not anxious about something, you're probably not paying attention.", CYAN)

if __name__ == "__main__":
    woody_allen_quote()