"""
Campbell's Soup Can #4544
Produced: 2026-08-12 00:00:02
Worker: inclusionAI: Ling 3.0 Tiny (free) (inclusionai/ling-3.0-tiny:free)
Employment: Volunteer
Flavor: Woody Allen Philosophy
Quality: ❌ (broken)

Made by Machine #0 - Production Line 0
Like Warhol's soup cans - same but different.
Each can is the same flavor, made by different hands.
"""

#!/usr/bin/env python3
"""
🎬 Woody Allen: Philosophical Quote Generator
    "A man can be a successful scientist, but he can never be a successful scientist."
"""

import time
import os
import sys
import termios
import tty

def clear_screen():
    os.system('clear' if os.name != 'nt' else 'cls')

def animate_typewriter(text, width=60, color_fore="white", color_bg="black", delay=0.04):
    """Animated typewriter effect with color."""
    for i, char in enumerate(text):
        print(f"\033[{color_fore}m{char}\033[0m", end='', flush=True)
        time.sleep(delay)
    print()

def get_woody_ascii_art():
    """Create an ASCII art representation of a Woody Allen style frame."""
    frame = [
        "  _____     ____     _    _____  _    _____  _     _____  ___    ",
        " |     |   |    |   / \\  |     | |  /     || |   |     ||   |  |   |",
        " |     |   |    |  /   \\ |     | | /     || |   |     ||   |  |   |",
        " |     |   |    | /_     \\|_____/ | |____  || |   |_____|  |___|  |   |",
        " |_____|   |____|    \\   /  /  /  |_____| |_|   |_____|  /  /   |   |",
        "   \u2502   \u2502     \u2502    \u2502   \u2502          \u2502   \u2502      \u2502   \u2502    \u2502    \u2502",
        "  \\__/ \\__/     \\__/     \\__/               \\__/           \\__/      \n",
    ]
    return "\n".join(frame)

def print_fancy_quote():
    """Print a visually stunning Woody Allen quote with animations."""
    # ANSI color codes
    CYAN = "\033[96m"
    YELLOW = "\033[93m"
    GREEN = "\033[92m"
    RED = "\033[91m"
    MAGENTA = "\033[95m"
    BLUE = "\033[94m"
    WHITE = "\033[97m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RESET = "\033[0m"
    BG_BLACK = "\033[40m"
    BG_CYAN = "\033[46m"
    BG_GREEN = "\033[42m"
    
    # Clear screen
    clear_screen()
    
    # Title
    print(f"\n{BOLD}{CYAN}╔═══════════════════════════════════════════╗")
    print(f"{CYAN}║     🎬  W O O D Y   A L L E N   STYLE 🎬     ║")
    print(f"{CYAN}╚═══════════════════════════════════════════╝")
    print(f"\n{YELLOW}{BOLD}╔═══════════════════════════════════════════╗")
    print(f"{YELLOW}{BOLD}║    I\'m going to show you a truly fine quote,║")
    print(f"{YELLOW}{BOLD}║    and I\'m going to explain it to you,║")
    print(f"{YELLOW}{BOLD}║    but I\'ll be a bit nervous about the time.║")
    print(f"{YELLOW}{BOLD}╚═══════════════════════════════════════════╝")
    print(f"\n")

    # ASCII Frame around the quote
    print(f"{CYAN}")
    print(f"     ┌{'─' * 58}┐")
    print(f"     │{CYAN}     ★  {RESET}★  {CYAN}      {RESET}★  │")
    print(f"     │{CYAN}  {CYAN}         ┌─────────────────────────────────┐  {CYAN}│")
    print(f"     │{CYAN}  {CYAN}  {GREEN}{BOLD}╭────────────────────────────────────────────╮{RESET}  {CYAN}│")
    print(f"     │{CYAN}  {CYAN}  │  {RED}{BOLD}║  {CYAN}  {GREEN}W O O D Y   A L L E N   S T Y L E{RESET}  {CYAN}│  │")
    print(f"     │{CYAN}  {CYAN}  │  {RED}{BOLD}║  {CYAN}  {GREEN}✨  {CYAN}  {RED}PHILIPPICAL✨{RESET} {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}    {CYAN}   ──────────┐{CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}      │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │  {CYAN}  │  │")
    print(f"     │{CYAN}  {CYAN}  │  {CYAN}  │  {CYAN}  {CYAN}     │ {CYAN}   │  │")
    print(f"     └──────────────────────────────────────┘")
    print(f"\n{YELLOW}{BOLD}║  \"{RED}I am not a man of science, but I am a scoundrel.║{RESET}\"")
    print(f"{CYAN}")
    print(f"     └{'─' * 58}┘")
    print(f"\n")

    # The Quote
    print(f"{BOLD}╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮")
    print(f"{CYAN}{BOLD}║  {GREEN}  ✦   ─────────────────────────────────────────────────────────────────────────────────────────────── ✦       ║")
    print(f"{CYAN}{BOLD}║  {GREEN}   ║  {RED}{BOLD}\"I am not a man of science, but I am a scoundrel.  ║{RESET}    ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}And my science is this: I never knew what I wanted  ║{RESET}     ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}until I found out I couldn't have it.  ║{RESET}       ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}And my scoundrelism is that I didn't want it.  ║{RESET}       ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I am a man, I am a scoundrel.  ║{RESET}           ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not afraid of death, I just don't want to be there.  ║{RESET} ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}But I'm not saying that's a reason for suicide.  ║{RESET}    ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}But I'm saying it's a reason for a very long delay.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I've been to the dentist. I've been to the doctor.  ║{RESET}    ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}And in both cases I've had to wait.  ║{RESET}            ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I am not a man of science, but I am a scoundrel.  ║{RESET}  ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}Life is terrible and nothing is worth doing.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}Everything I think is a beautiful idea and nothing at all is the slightest bit like it.  ║{RESET} ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I don't know if I'm a man or not but I'm certainly scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I have a very peculiar philosophy that in all things you should  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}take the scenic route.  ║{RESET}           ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}That's my philosophy.  ║{RESET}            ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}It's the best philosophy for the human condition.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I am not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET}   ║{CYAN}  ")
    print(f"{CYAN}{BOLD}║  ║  {RED}{BOLD}   ║  {RED}I'm not a man of science, but I am a scoundrel.  ║{RESET